DAX = {
    'ADS.DE' : 'Adidas AG ',
    'ALV.DE' : 'Allianz SE',
    'BAS.DE' : 'Basf SE',
    'BAYN.DE': 'Bayer AG',
    'BEI.DE' : 'Beiersdorf Aktiengesellschaft',
    'BMW.DE' : 'Bayerische Motoren Werke AG',
    'CBK.DE' : 'Commerzbank AG',
    #'CON.DE': 'Continental AG',
    'DAI.DE' : 'Daimler AG',
    'DB1.DE' : 'Deutsche Boerse AG',
    'DBK.DE' : 'Deutsche Bank AG',
    'DPW.DE' : 'Deutsche Post AG',
    'DTE.DE' : 'Deutsche Telekom AG',
    'EOAN.DE': 'E.On SE',
    'FME.DE' : 'Fresenius Medical Care Corporation',
    'FRE.DE' : 'Fresenius SE & Co KGaA',
    'HEI.DE' : 'HeidelbergCement AG',
    'HEN3.DE': 'Henkel AG & Co KGaA',
    'IFX.DE' : 'Infineon Technologies AG',
    'LHA.DE' : 'Deutsche Lufthansa AG',
    'LIN.DE' : 'Linde AG',
    'LXS.DE' : 'Lanxess AG',
    'MRK.DE' : 'Merck KGaA',
    'MUV2.DE': 'Muenchener Rueckversicherungs AG',
    'RWE.DE' : 'RWE AG',
    'SAP.DE' : 'Sap AG',
    'SDF.DE' : 'K+S Aktiengesellschaft',
    'SIE.DE' : 'Siemens AG',
    'TKA.DE' : 'ThyssenKrupp AG',
    'VOW3.DE': 'Volkswagen AG'
}

MDAX = {
    'ARL.DE' : 'Aareal Bank AG',
    'BNR.DE' : 'Brenntag AG',
    'BOSS.DE': 'HUGO BOSS N',
    'BYW6.DE': 'BayWa AG',
    'CLS1.DE': 'Celesio AG',
    'DEQ.DE' : 'Deutsche EuroShop AG',
    'DUE.DE' : 'Duerr AG',
    'DWNI.DE': 'Deutsche Wohnen AG',
    'EAD.DE' : 'European Aeronautic Defence and Space NV',
    'FIE.DE' : 'Fielmann AG',
    'FPE3.DE': 'Fuchs Petrolub AG',
    'FRA.DE' : 'Fraport AG',
    'G1A.DE' : 'GEA Group Aktiengesellschaft',
    'GBF.DE' : 'Bilfinger SE',
    'GFJ.DE' : 'Gagfah SA',
    'GIB.DE' : 'GSW Immobilien AG',
    'GIL.DE' : 'Gildemeister AG',
    'GWI1.DE': 'Gerry Weber International AG',
    'GXI.DE' : 'Gerresheimer AG',
    'HDD.DE' : 'Heidelberger Druckmaschinen AG',
    'HHFA.DE': 'Hamburger Hafen und Logistik AG',
    'HNR1.DE': 'Hannover Rueckversicherung AG',
    'HOT.DE' : 'Hochtief AG',
    'KCO.DE' : 'Kloeckner & Co Aktiengesellschaft',
    'KD8.DE' : 'Eurotex Finanz, Inc.',
    'KRN.DE' : 'Krones AG',
    'KU2.DE' : 'KUKA Aktiengesellschaft',
    'LEO.DE' : 'Leoni AG',
    'MAN.DE' : 'MAN SE',
    'MEO.DE' : 'Metro AG',
    'MTX.DE' : 'MTU Aero Engines Holding AG',
    'NDA.DE' : 'Aurubis AG',
    'PSM.DE' : 'ProSiebenSat.1 Media AG',
    'PUM.DE' : 'Puma AG',
    'RAA.DE' : 'Rational AG',
    'RHK.DE' : 'Rhoen Klinikum AG',
    'RHM.DE' : 'Rheinmetall AG',
    'SAZ.DE' : 'STADA Arzneimittel AG',
    'SGL.DE' : 'SGL Carbon SE',
    'SKYD.DE': 'Sky Deutschland AG',
    'SPR.DE' : 'Axel Springer AG',
    'SY1.DE' : 'Symrise AG',
    'SZG.DE' : 'Salzgitter AG',
    'SZU.DE' : 'Suedzucker AG',
    'TEG.DE' : 'TAG Immobilien AG',
    'TLX.DE' : 'TALANX N',
    'TUI1.DE': 'TUI AG',
    'VOS.DE' : 'Vossloh AG',
    'WCH.DE' : 'Wacker Chemie AG ',
    'WIN.DE' : 'Wincor Nixdorf Aktiengesellschaft'
}

SDAX = {
    '2HR.DE' : 'H&R',
    'AAD.DE' : 'Amadeus Fire AG',
    'AB1.DE' : 'Air Berlin PLC',
    'AOX.DE' : 'ALSTRIA OFFICE REIT AG',
    'B5A.DE' : 'BAUER Aktiengesellschaft',
    'BAF.DE' : 'Balda AG',
    'BDT.DE' : 'Bertrandt AG',
    'BIO3.DE': 'Biotest AG',
    'CEV.DE' : 'CENTROTEC Sustainable AG',
    'COM.DE' : 'comdirect bank AG',
    'CWC.DE' : 'CeWe Color Holding AG',
    'DAZ.DE' : 'DIC Asset AG',
    'DBA.DE' : 'Deutsche Beteiligungs AG',
    'DEX.DE' : 'Delticom AG',
    'DEZ.DE' : 'Deutz AG',
    'DUE.DE' : 'Duerr AG',
    'EV4.DE' : 'Constantin Medien AG',
    'EVD.DE' : 'CTS Eventim AG',
    'GFK.DE' : 'GfK AG',
    'GLJ.DE' : 'Grenkeleasing AG',
    'GMM.DE' : 'Grammer AG',
    'GSC1.DE': 'GESCO N',
    'HAB.DE' : 'Hamborner AG',
    'HAW.DE' : 'Hawesko Holding AG',
    'HBH3.F' : 'HORNBACH HOLDING VZ',
    'HDD.DE' : 'Heidelberger Druckmaschinen AG',
    'HLG.DE' : 'Highlight Communications AG',
    'INH.DE' : 'Indus Holding AG',
    'IVG.DE' : 'IVG Immobilien AG',
    'JUN3.DE': 'Jungheinrich AG',
    'KWS.DE' : 'KWS saat AG',
    'MLP.DE' : 'MLP AG',
    'NOEJ.DE': 'NORMA GROUP N',
    'O2C.DE' : 'C.A.T. Oil AG',
    'P1Z.DE' : 'PATRIZIA Immobilien AG',
    'PMO.DE' : 'PRIME OFFICE REIT',
    'PRA.DE' : 'Praktiker AG',
    'S4A.DE' : 'SMT Scharf AG',
    'SAX.DE' : 'Stroeer Out-of-Home Media AG',
    'SFQ.DE' : 'SAF Holland SA',
    'SIX2.DE': 'Sixt AG',
    'SK1A.DE': 'SKW STAHL-MET N',
    'SKB.DE' : 'Koenig & Bauer AG',
    'SLT.DE' : 'Schaltbau Holding AG',
    'TIM.DE' : 'Tipp24 AG',
    'TTI.DE' : 'Tom Tailor Holding AG',
    'TTK.DE' : 'Takkt AG',
    'VT9.DE' : 'VTG Aktiengesellschaft',
    'WAC.DE' : 'Wacker Neuson SE'
}

TECDAX = {
    'ADV.DE' : 'ADVA AG Optical Networking',
    'AFX.DE' : 'Carl Zeiss Meditec AG',
    'AIXA.DE': 'Aixtron AG',
    'BBZA.DE': 'BB Biotech AG',
    'BC8.DE' : 'Bechtle AG',
    'COK.DE' : 'Cancom IT Systeme AG',
    'DLG.DE' : 'Dialog Semiconductor PLC',
    'DRI.DE' : 'Drillisch AG',
    'DRW3.DE': 'Draegerwerk AG & Co KGaA',
    'EUCA.DE': 'EUROMICRON N',
    'EVT.DE' : 'Evotec AG',
    'FNTN.DE': 'freenet AG',
    'JEN.DE' : 'Jenoptik AG',
    'KBC.DE' : 'Kontron AG',
    'LPK.DE' : 'LPKF Laser & Electronics AG',
    'MOR.DE' : 'MorphoSys AG',
    'NDX1.DE': 'Nordex AG',
    'O1BC.DE': 'Xing AG',
    'PFV.DE' : 'Pfeiffer Vacuum Technology AG',
    'PSAN.DE': 'PSI Aktiengesellschaft',
    'QCE.F'  : 'GLOBAL PVQ',
    'QIA.DE' : 'Qiagen NV',
    'QSC.DE' : 'QSC AG',
    'S92.DE' : 'SMA Solar Technology AG',
    'SBS.DE' : 'Stratec Biomedical AG',
    'SMHN.DE': 'SUESS MICROTEC N',
    'SOW.DE' : 'Software AG',
    'SRT3.DE': 'Sartorius AG',
    'SWV.DE' : 'SolarWorld AG',
    'UTDI.DE': 'United Internet AG',
    'WDI.DE' : 'Wirecard AG'
}

DJI = {
    'AA'  : 'Alcoa Inc.',
    'AXP' : 'American Express Company',
    'BA'  : 'The Boeing Company',
    'BAC' : 'Bank of America Corporation',
    'CAT' : 'Caterpillar Inc.',
    'CSCO': 'Cisco Systems, Inc.',
    'CVX' : 'Chevron Corporation',
    'DD'  : 'E. I. du Pont de Nemours and Company',
    'DIS' : 'The Walt Disney Company',
    'GE'  : 'General Electric Company',
    'HD'  : 'The Home Depot, Inc.',
    'HPQ' : 'Hewlett-Packard Company',
    'IBM' : 'International Business Machines Corporation',
    'INTC': 'Intel Corporation',
    'JNJ' : 'Johnson & Johnson',
    'JPM' : 'JPMorgan Chase & Co.',
    'KO'  : 'The Coca-Cola Company',
    'MCD' : 'McDonald\'s Corp.',
    'MMM' : '3M Company',
    'MRK' : 'Merck & Co. Inc.',
    'MSFT': 'Microsoft Corporation',
    'PFE' : 'Pfizer Inc.',
    'PG'  : 'Procter & Gamble Co.',
    'T'   : 'AT&T, Inc.',
    'TRV' : 'The Travelers Companies, Inc.',
    'UNH' : 'UnitedHealth Group Incorporated',
    'UTX' : 'United Technologies Corp.',
    'VZ'  : 'Verizon Communications Inc.',
    'WMT' : 'Wal-Mart Stores Inc.',
    'XOM' : 'Exxon Mobil Corporation'
}

NDX = {
    'AAPL':    'Apple Inc.',
#   'ADBE':    'Adobe Systems Inc.',
#   'ADP':     'Automatic Data Processing, Inc.',
#   'ADSK':    'Autodesk, Inc.',
#   'AKAM':    'Akamai Technologies, Inc.',
#   'ALTR':    'Altera Corp.',
#   'ALXN':    'Alexion Pharmaceuticals, Inc.',
#   'AMAT':    'Applied Materials Inc.',
#   'AMGN':    'Amgen Inc.',
    'AMZN':    'Amazon.com Inc.',
#   'APOL':    'Apollo Group Inc.',
#   'ATVI':    'Activision Blizzard, Inc.',
#   'AVGO':    'Avago Technologies Limited',
#   'BBBY':    'Bed Bath & Beyond Inc.',
#   'BIDU':    'Baidu, Inc.',
#   'BIIB':    'Biogen Idec Inc.',
#   'BMC':     'BMC Software Inc.',
#   'BRCM':    'Broadcom Corp.',
#   'CA':      'CA Technologies',
#   'CELG':    'Celgene Corporation',
#   'CERN':    'Cerner Corporation',
#   'CHKP':    'Check Point Software Technologies Ltd.',
#   'CHRW':    'CH',    'Robinson Worldwide Inc.',
#   'CMCSA':   'Comcast Corporation',
#   'COST':    'Costco Wholesale Corporation',
#   'CSCO':    'Cisco Systems, Inc.',
#   'CTSH':    'Cognizant Technology Solutions Corporation',
#   'CTXS':    'Citrix Systems, Inc.',
#   'DELL':    'Dell Inc.',
#   'DLTR':    'Dollar Tree, Inc.',
#   'DTV':     'DIRECTV',
    'EA':      'Electronic Arts Inc.',
#   'EBAY':    ' eBay Inc.',
#   'ESRX':    'Express Scripts Holding Company',
#   'EXPD':    'Expeditors International of Washington Inc.',
#   'EXPE':    'Expedia Inc.',
#   'FAST':    'Fastenal Company',
    'FB':      'Facebook, Inc.',
#   'FFIV':    'F5 Networks, Inc.',
#   'FISV':    'Fiserv, Inc.',
#   'FLEX':    'Flextronics International Ltd.',
#   'FOSL':    'Fossil, Inc.',
#   'GILD':    'Gilead Sciences Inc.',
#   'GMCR':    'Green Mountain Coffee Roasters Inc.',
#   'GOLD':    'Randgold Resources Limited',
    'GOOG':    'Google Inc.',
#   'GRMN':    'Garmin Ltd.',
#   'HSIC':    'Henry Schein, Inc.',
    'INTC':    'Intel Corporation',
#   'INTU':    'Intuit Inc.',
#   'ISRG':    'Intuitive Surgical, Inc.',
#   'KLAC':    'KLA-Tencor Corporation',
#   'LIFE':    'Life Technologies Corporation',
#   'LINTA':   'Liberty Interactive Corporation',
    'LLTC':    'Linear Technology Corporation',
#   'LRCX':    'Lam Research Corporation',
#   'MAT':     'Mattel, Inc.',
#   'MCHP':    'Microchip Technology Inc.',
#   'MDLZ':    'Mondelez International, Inc.',
#   'MNST':    'Monster Beverage Corporation',
#   'MRVL':    'Marvell Technology Group Ltd.',
    'MSFT':    'Microsoft Corporation',
#   'MU':      'Micron Technology Inc.',
#   'MXIM':    'Maxim Integrated Products, Inc.',
#   'MYL':     'Mylan, Inc.',
#   'NFLX':    'Netflix, Inc.',
#   'NTAP':    'NetApp, Inc.',
#   'NUAN':    'Nuance Communications, Inc.',
    'NVDA':    'NVIDIA Corporation',
#   'NWSA':    'News Corp.',
    'ORCL':    'Oracle Corporation',
#   'ORLY':    'O'Reilly Automotive Inc.',
#   'PAYX':    'Paychex, Inc.',
#   'PCAR':    'PACCAR Inc.',
#   'PCLN':    'priceline.com Incorporated',
#   'PRGO':    'Perrigo Co.',
#   'QCOM':    'QUALCOMM Incorporated',
#   'RIMM':    'Research In Motion Limited',
#   'ROST':    'Ross Stores Inc.',
    'SBUX':    'Starbucks Corporation',
#   'SHLD':    'Sears Holdings Corporation',
#   'SIAL':    'Sigma-Aldrich Corporation',
#   'SIRI':    'SIRIUS XM Radio Inc.',
    'SNDK':    'SanDisk Corp.',
#   'SPLS':    'Staples, Inc.',
#   'SRCL':    'Stericycle, Inc.',
#   'STX':     'Seagate Technology Public Limited Company',
#   'SYMC':    'Symantec Corporation',
    'TXN':     'Texas Instruments Inc.',
#   'VIAB':    'Viacom, Inc.',
    'VMED':    'Virgin Media, Inc.',
#   'VOD':     'Vodafone Group Public Limited Company',
#   'VRSN':    'VeriSign, Inc.',
#   'VRTX':    'Vertex Pharmaceuticals Incorporated',
#   'WCRX':    'Warner Chilcott plc',
#   'WFM':     'Whole Foods Market, Inc.',
#   'WYNN':    'Wynn Resorts Ltd.',
#   'XLNX':    'Xilinx Inc.',
#   'XRAY':    'DENTSPLY International Inc.',
    'YHOO':    'Yahoo! Inc.'
}

INDEXES = {
    '^GDAXI' : 'Deutscher Aktienindex',
    '^MDAXI' : 'Mid-Cap DAX',
    '^SDAXI' : 'Small-Cap DAX',
    '^TECDAX': 'Technologie DAX',
    '^DJI'   : 'Dow Jones Industrial Average',
    '^GSPC'  : 'Standard & Poors',
    '^NDX'   : 'Nasdaq-100'
}

MARKET_NAMES = ['INDEXES', 'DAX', 'MDAX', 'SDAX', 'TECDAX', 'DJI', 'NDX']
MARKET_REFS  = [ INDEXES ,  DAX ,  MDAX ,  SDAX ,  TECDAX ,  DJI ,  NDX ]

